### ISSUE TITLE
Cannot connect to the RTM API using Bot tokens (xoxb-...)

### ISSUE THREAD

**Issue by Dombo** [go-joe/slack-adapter#16]
First off, cool project - I like it especially the addition of the Cron adapter + multi platform support.

What is the advised approach to using this adapter now? 
It's unclear whether we should switch to the Events API and parse every message event the bot receives or if there is a workaround for the RTM API?

```
slack-go/slack2020/06/07 18:09:42 rtm.go:71: Using URL: 
slack-go/slack2020/06/07 18:09:42 websocket_managed_conn.go:181: Failed to start or connect to RTM: not_allowed_token_type
slack-go/slack2020/06/07 18:09:42 websocket_managed_conn.go:147: reconnection 1 failed: not_allowed_token_type reconnecting in 100ms
```

An ongoing discussion over at the API client. https://github.com/slack-go/slack/issues/654

**Comment by fgrosse** [comment]
Hey Dombo, seems my own slack bot is still working as expected but I will check out the issue you referenced to understand what the problem might be :)

**Comment by fgrosse** [comment]
Okay so if I understand that issue correctly, apparently Slack has decided they don't like websockets anymore (the RTM API) and instead want their users to migrate to the new Events API which  basically relies on HTTP callbacks that we get from the slack servers :thinking: 

Even though I very much dislike this change from Slack, we should enable it in the joe slack adapter as well. It should not be too hard but requires some effort. I can look into it this week :)

**Comment by Dombo** [comment]
I've read the documentation - it seems they've split their apps in to two 'styles' now. Classic Apps were created before a specific date or created now through a specific link still work - New Apps (think they are just calling them apps actually) have a new token style that will fail auth checks over the RTM API.

Before you put too much work in, I've put some steps below for how a new user of this adapter can workaround this. In the long run I suspect they will deprecate the RTM API or leave it unsupported. 

### Workaround

Visit https://api.slack.com/apps?new_classic_app=1 and then complete the "Create a Slack App (Classic)" form.

**App Home** -> **Add Legacy Bot User**.

Go and click **Install app**

On the following page, if you're a slack admin, click **Allow**.  If you're not you'll have to request approval.

Once the app is installed, under the **Install App** settings, copy your **Bot User OAuth Access Token**. You'll want the token startin with `xoxb-` which will work with the RTM API.

**Comment by fgrosse** [comment]
I created an implementation that _should_ work via e305d72 but so far I just hacked on it and its still lacking any unit tests. Also I'm unsure how I can test this manually, given I do not want to mess with my existing bots so I would have to deploy a new app into some Slack workspace.

@Dombo you don't happen to be able to give this a try on your systems? Even a review would be appreciated so I will open a PR now just to enable that. Once we know it looks about right I will invest more time in unit testing it.

**Comment by Dombo** [comment]
@fgrosse I'll get to it tonight after work.

**Comment by Dombo** [comment]
I checked out your branch and couldn't get it to authenticate - still got the same error.

```
slack-go/slack2020/06/11 22:20:54 rtm.go:71: Using URL: 
slack-go/slack2020/06/11 22:20:54 websocket_managed_conn.go:181: Failed to start or connect to RTM: not_allowed_token_type
slack-go/slack2020/06/11 22:20:54 websocket_managed_conn.go:147: reconnection 1 failed: not_allowed_token_type reconnecting in 100ms
slack-go/slack2020/06/11 22:20:54 websocket_managed_conn.go:177: Connecting to RTM
```

I just created a new slack app and gave it the bot scope + some oauth scopes for things like reading @ mentions to test it. Maybe that will help you setup a reproducible failure state?

**Comment by Dombo** [comment]
Disregard my previous comment - this approach looks good.

The good news: no more not_allowed_token_type

The bad news: It's failing to verify token at `go/pkg/mod/github.com/go-joe/slack-adapter/v2@v2.0.1-0.20200611132151-e305d7279be0/events_api.go:64`

I tried modifying my local version to use NoVerifyToken and passing the specific Verification Token (which they say is legacy). It might be my configuration but I think the verification logic isn't meant to use the same token as you do for authentication.

I might be mistaken though https://api.slack.com/authentication/verifying-requests-from-slack

**Comment by Dombo** [comment]
Seems the example in the slack API client led you astray - it's poorly worded. Check this issue for someone else running into a similar issue: https://github.com/slack-go/slack/issues/705

So the adapter needs to take two secrets now rather than one, the token (for API communication) and the signing secret/verification token (for verifying the request is free from interference/genuine)

They seem to be sunsetting the verification token in favour of the signing secret as well :rage: using language like "**For a while**, you'll see two secrets side-by-side in the app management panel:" and "We strongly recommend you only use the Signing Secret from now on."

Unsure whether you want this discussion on the PR or in this issue?

**Comment by Dombo** [comment]
I took another look - seems like when it comes time to check the token it's explicitly set to the Slack API token not the verification token, I tried overriding it (setting it explicitly to my verification token) at `github.com/go-joe/slack-adapter/v2@v2.0.1-0.20200611132151-e305d7279be0/events_api.go:64` but by the time it was calling the comparator function it was comparing "xoxb-..." with "UB...."

**Comment by fgrosse** [comment]
Hey @Dombo I know it took quiet some time to get #17 and #18 merged into the main branch but I just did the final merge and tagged it as v2.1.0 :tada:

**Comment by Dombo** [comment]
Good to hear, thanks for working with me on it.
