### ISSUE TITLE
HTTP Health Check Endpoint for Events API

### ISSUE THREAD

**Issue by jonwinton** [go-joe/slack-adapter#19]
Hi! I'm just getting started with this library and have a demo app using the events API. I need to deploy the app to AWS ECS, and for that I'll need to set up a health check on the load balancer that exposes the endpoint. I know the [http-server](https://github.com/go-joe/http-server) module exists, but the load balancer health check needs to be pointed at the same port that is receiving traffic. 

What's the best way to go about this? I considered adding a `/ping` endpoint to the sever spun up in this module, but I hope someone else has solved this already.

Thanks!

**Comment by fgrosse** [comment]
Sorry for never answering here. Looks like this fell between the cracks and then I completely forgot about this request.
Implementing a custom health check endpoint which would run on the same port as the event API server is now supported via #21 :tada: (see unit tests in the PR)

**Comment by jonwinton** [comment]
No worries, thanks!
